# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\cardLastMatchTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(682, 881)
        Form.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.searchInfo = QtWidgets.QHBoxLayout()
        self.searchInfo.setContentsMargins(-1, 10, -1, 10)
        self.searchInfo.setSpacing(5)
        self.searchInfo.setObjectName("searchInfo")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.searchInfo.addWidget(self.label)
        self.searchCounter = QtWidgets.QLabel(Form)
        self.searchCounter.setObjectName("searchCounter")
        self.searchInfo.addWidget(self.searchCounter)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.searchInfo.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.searchInfo.addWidget(self.label_2)
        self.allMatchCount = QtWidgets.QLabel(Form)
        self.allMatchCount.setObjectName("allMatchCount")
        self.searchInfo.addWidget(self.allMatchCount)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.searchInfo.addWidget(self.label_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.searchInfo.addItem(spacerItem)
        self.gridLayout.addLayout(self.searchInfo, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 5)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setCheckable(False)
        self.pushButton_3.setAutoExclusive(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setCheckable(False)
        self.pushButton_4.setAutoExclusive(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.nameLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel.setFont(font)
        self.nameLabel.setStyleSheet("background:#e3e3e3;padding:15px")
        self.nameLabel.setObjectName("nameLabel")
        self.horizontalLayout_2.addWidget(self.nameLabel)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.photosFrame = QtWidgets.QFrame(Form)
        self.photosFrame.setMinimumSize(QtCore.QSize(682, 700))
        self.photosFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.photosFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.photosFrame.setObjectName("photosFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.photosFrame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout.addWidget(self.photosFrame, 1, 0, 1, 1)

        self.retranslateUi(Form)
        self.pushButton_3.clicked.connect(Form.startSearch)
        self.pushButton_4.clicked.connect(Form.reinit)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Prešol mi:"))
        self.searchCounter.setText(_translate("Form", "0"))
        self.label_3.setText(_translate("Form", " ludzi"))
        self.label_2.setText(_translate("Form", "Sce me:"))
        self.allMatchCount.setText(_translate("Form", "0"))
        self.label_4.setText(_translate("Form", " ludzi"))
        self.pushButton_3.setText(_translate("Form", "Hledaj"))
        self.pushButton_4.setText(_translate("Form", "Zobač znova"))
        self.nameLabel.setText(_translate("Form", "Toto dzivče me scelo"))

