# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(2177, 739)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.likeCount = QtWidgets.QScrollArea(Form)
        self.likeCount.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.likeCount.setWidgetResizable(True)
        self.likeCount.setObjectName("likeCount")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 2133, 621))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(25)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.likeCount.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.likeCount, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.versionLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.versionLabel.setFont(font)
        self.versionLabel.setObjectName("versionLabel")
        self.horizontalLayout.addWidget(self.versionLabel)
        self.logoutButton = QtWidgets.QPushButton(Form)
        self.logoutButton.setObjectName("logoutButton")
        self.horizontalLayout.addWidget(self.logoutButton)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.locationInput = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.locationInput.sizePolicy().hasHeightForWidth())
        self.locationInput.setSizePolicy(sizePolicy)
        self.locationInput.setAlignment(QtCore.Qt.AlignCenter)
        self.locationInput.setReadOnly(True)
        self.locationInput.setObjectName("locationInput")
        self.horizontalLayout.addWidget(self.locationInput)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.likesLeft = QtWidgets.QSpinBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.likesLeft.sizePolicy().hasHeightForWidth())
        self.likesLeft.setSizePolicy(sizePolicy)
        self.likesLeft.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.likesLeft.setMaximum(99999)
        self.likesLeft.setObjectName("likesLeft")
        self.horizontalLayout.addWidget(self.likesLeft)
        self.likesLeftWaitInput = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.likesLeftWaitInput.sizePolicy().hasHeightForWidth())
        self.likesLeftWaitInput.setSizePolicy(sizePolicy)
        self.likesLeftWaitInput.setInputMask("")
        self.likesLeftWaitInput.setObjectName("likesLeftWaitInput")
        self.horizontalLayout.addWidget(self.likesLeftWaitInput)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.superLikesLeft = QtWidgets.QSpinBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.superLikesLeft.sizePolicy().hasHeightForWidth())
        self.superLikesLeft.setSizePolicy(sizePolicy)
        self.superLikesLeft.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.superLikesLeft.setMaximum(99999)
        self.superLikesLeft.setObjectName("superLikesLeft")
        self.horizontalLayout.addWidget(self.superLikesLeft)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.comboBox = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.comboBox.setCurrentIndex(1)
        self.logoutButton.clicked.connect(Form.logout)
        self.pushButton_2.clicked.connect(Form.refresh)
        self.comboBox.currentIndexChanged['QString'].connect(Form.showPeople)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.versionLabel.setText(_translate("Form", "Marián@Tinder"))
        self.logoutButton.setText(_translate("Form", "Odláš me"))
        self.label_2.setText(_translate("Form", "Tu mi:"))
        self.label.setText(_translate("Form", "Pekniačky:"))
        self.likesLeft.setPrefix(_translate("Form", " "))
        self.label_3.setText(_translate("Form", "Super-Pekniačky"))
        self.superLikesLeft.setPrefix(_translate("Form", " "))
        self.label_4.setText(_translate("Form", "Zobač:"))
        self.comboBox.setCurrentText(_translate("Form", "10"))
        self.comboBox.setItemText(0, _translate("Form", "5"))
        self.comboBox.setItemText(1, _translate("Form", "10"))
        self.comboBox.setItemText(2, _translate("Form", "25"))
        self.comboBox.setItemText(3, _translate("Form", "50"))
        self.comboBox.setItemText(4, _translate("Form", "100"))
        self.comboBox.setItemText(5, _translate("Form", "200"))
        self.pushButton_2.setText(_translate("Form", "Obnov"))

